# Generated by Django 4.2.5 on 2023-12-25 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=100)),
                ('info_product', models.TextField(max_length=1500, verbose_name='Описание продукта')),
                ('foto', models.ImageField(upload_to='foto/', verbose_name='Фотография продукта')),
            ],
        ),
    ]
